name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: checkout
      uses: actions/checkout@v4

    - name: install dev dependencies
      run: npm install

    - name: build the actions
      run: npm run build

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

    - name: sync tag
      if: github.ref_type == 'tag'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.PUBLISH_BUILD_GITHUB_TOKEN }}
        script: |
          const branchName = context.payload.base_ref.replace('refs/heads/', '');

          const list = await github.rest.git.listMatchingRefs({
            owner: 'volbobvol',
            repo: 'action-target',
            ref: 'heads/' + branchName
          });
          console.log(JSON.stringify(list));
          await github.rest.git.createRef({
            owner: 'volbobvol',
            repo: 'action-target',
            ref: 'refs/tags/${{ github.ref_name }}',
            sha: list.data[0].object.sha
          })

    - name: pushes build result
      if: github.ref_type == 'branch'
      uses: cpina/github-action-push-to-another-repository@v1.7.2
      env:
        API_TOKEN_GITHUB: ${{ secrets.PUBLISH_BUILD_GITHUB_TOKEN }}
      with:
        source-directory: './actions/submit-signing-request/dist'
        destination-github-username: 'volbobvol'
        destination-repository-name: 'action-target'
        user-name: GHA build process
        create-target-branch-if-needed: true
        commit-message: Original commit message - ${{ github.event.head_commit.message }}
        target-branch: ${{ github.ref_name }}